### ISSUE TITLE
API Server offline?

### ISSUE THREAD

**Issue by FoxXxHater** [klyqa/home-assistant-integration#49]
The Klyqa integration dosnt work...

**Comment by FoxXxHater** [comment]
Here is the error log from ha

![image](https://github.com/klyqa/home-assistant-integration/assets/54017453/639fed80-1a5f-4166-b43b-feea4d86166e)

**Comment by gh-andyn** [comment]
I'm having the same issue...just tried to connect my new klyqa lamps with ha. Same problem and couldn't identify the actual root cause.
