### ISSUE TITLE
Klyqa shows up in the integrations of HA but no device/lamp

### ISSUE THREAD

**Issue by PietGoldberg** [klyqa/home-assistant-integration#50]
I made klyqa available in the integrations but the devices/lamps are not added or recognized after i added my klyqa-account.
Please let me know if there is a trick to get them recognized by ha. no device, no entity is shown. 
I am running HASS OS on raspberry pi 4

**Comment by hojo0590** [comment]
Possibly you're running a newer version of HomeAssistant than the klyqa integration can work with. You can monkey path the `__init__.py` when copying the source into the `custom_components`:
L152:
```python
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
```

I got it as far as then entities are found but I can't control them yet...
