### ISSUE TITLE
The intrigration is loaded but does not manage to create lamps in my Homeassistant.

### ISSUE THREAD

**Issue by 19Zer0s** [klyqa/home-assistant-integration#55]
Hello, I have been having problems with my Homeassistant integration for a few days now 
The intrigration is loaded but does not manage to create lamps in my Homeassistant.
I have not been able to use my lamps for the last 4 weeks due to a defect in my Accespoint. But for a good 5 days now I just can't get the whole thing to work. I have already reinstalled my HAOS, but that didn't help either.

I get a few Warnings and Errors in the Logs:
[Error while setting up klyqa platform for light.log](https://github.com/user-attachments/files/15952594/Error.while.setting.up.klyqa.platform.for.light.log)
[Warning async_run_job is deprecated.log](https://github.com/user-attachments/files/15952596/Warning.async_run_job.is.deprecated.log)
[Error doing job.log](https://github.com/user-attachments/files/15952597/Error.doing.job.log)

Can anyone help me with this error?

**Comment by dennisjonda** [comment]
Same problem here.. :/

**Comment by Unleadedat** [comment]
It seems that the Integration is broken with Home Assistant Core Version higher than 2024.5.5

**Comment by 19Zer0s** [comment]
> Same problem here.. :/

I wrote to support and that was the answer....


3 July 2024, 16:30 CEST

Hy!
 
Our Home Assistant is currently still under development, we are working on fixing the problem to make it functional again, but due to our limited resources it may take some time.
 
 
Best regards,
 
Steve from Klyqa

**Comment by dennisjonda** [comment]
@19Zer0s Good news! I've addressed the issue you reported with the Klyqa integration. I've made several changes to fix the lamp creation problem and resolve the warnings you were seeing in the logs. 

I've tested these changes with G96 Vintage Lamp, E27 Color, and E14 Color models, and they're working correctly on my end.

Could you please check if this [fix](https://github.com/klyqa/home-assistant-integration/pull/56) resolves the issue for you as well?

**Comment by 19Zer0s** [comment]
@dennisjonda 
Thank you for fixing the issue.
I have just successfully tested the integration with the ‘E14 Color’ and the ‘E27 Color’ lamps on the following version!
Core: 2024.10.3
Supervisor: 2024.10.2
Operating System: 13.2
Frontend: 20241002.3
